name: Demo trigger events

on: 
  # Webhook events
  push:
    branches: 
      - main
      - feat/*
  pull_request:
    branches:
      - main
  issues:
    types: 
      - opened
      - closed
  
  # Schedule events
  schedule:
    - cron: 0 0 * * * 
    - cron: 0 9 * * 0 
  # Manual events
  workflow_dispatch:
    inputs:
      yourName: 
        required: true
        default: My friend
      areYouFeelingGood:
        required: true
        type: boolean
      howDoYouFindGithubActions:
        required: false
        type: choice
        options:
          - Awesome
          - Okay
          - Better not say

env:
  MY_NAME: Bo
  GREETING: Hi
      

jobs:
  Greeting:
    runs-on: ubuntu-latest
    steps:
      - name: "Greeting step expect Hi"
        run: |
          echo $GREETING $MY_NAME
          echo "${{env.GREETING}} ${{env.MY_NAME}}
        if: env.MY_NAME == 'Bo'
  Greeting2:
    runs-on: ubuntu-latest
    env:
      GREETING: good morning
    steps:
      - name: "Greeting step expects good morning."
        run: echo $GREETING $MY_NAME
      - name: "Greeting step expects good afternoon."
        run: echo $GREETING $MY_NAME
        env:
          GREETING: good afternoon.

  Job2:
    runs-on: ubuntu-latest
    needs: [Greeting]
    steps:
      - name: Step2
        run: echo "${{ github.actor }} is learning GitHub Actions"
      - name: Step3
        run: echo "Great!"
        if: ${{ inputs.areYouFeelingGood }}
      - name: Step4
        run: echo "No worries, I am here with you!"
        if: ${{ inputs.areYouFeelingGood == false }}
      
